name: Update README Live Activity

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    name: Update GitHub Activity
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update README with recent activity
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
